### ISSUE TITLE
[Bug] Spurious host down detections?

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#559]
### Is there an existing issue for this?

- [x] I have searched the existing issues (open and closed) and the documentation

### Current Behavior

After installing the latest update today, I get very frequent Host Up/Down notifications.  The reported address is my VPN endpoint.

I doubt that the endpoint has any actual problems since I'm not seeing any internet disruptions.

### Environment

OS: Raspberry Pi (Debian 12)

**Comment by leiweibau** [comment]
With the exception of WAN IP detection and the outsourcing of the speed test, there were no changes to the scan script itself. Most of the changes in this update were languages, the consequences of changing the installation directory, and the integration of the additional database. This work was mainly done in the frontend and in the installation and update scripts. So unfortunately, I can't offer you an explanation for your observation at this time.

**Comment by hspindel** [comment]
You said there was a change to the WAN IP detection.  That's a possible source for the issue.

![Image](https://github.com/user-attachments/assets/a9b73716-fb56-4feb-b406-d4960215ca85)
![Image](https://github.com/user-attachments/assets/19470cbb-072b-4177-b9fa-64a59888d5f1)

**Comment by leiweibau** [comment]
During my test remote, I encountered a phenomenon where the WAN IP could not always be determined, and the script aborted due to “unexpected responses” or “incorrect responses” (completely, not just the determination of the WAN IP). I addressed this with the change. Now the question is: are you only noticing it now because the script no longer aborts and is therefore able to respond to it, or have I implemented something incorrectly? I'll take another look at it in the next few days.

**Comment by hspindel** [comment]
I tried to find something in the logs.

IP_changes.log shows only an expected change (once) when I turned my VPN back on.

Is there another log I can look at (or attach)?  

I looked through the code, and if I'm reading it correctly you are using curl to obtain the WAN IP.  I looked up how to do that, and found this page:

https://linuxconfig.org/how-to-use-curl-to-get-public-ip-address

I then tried all of the examples on that page, and they all worked except 'bot.whatismyipaddress.com' which gets a DNS resolution failure.

Maybe I've provided some useful info.  Thanks for looking at this.

**Comment by leiweibau** [comment]
Since I am somewhat dissatisfied with the fact that the logs are only available for a few minutes, I will now write them to the database in parallel so that past logs from the last 2-3 days are also available. For some time now, I have been “dreaming” of a small “dashboard”-like overview where such things could perhaps be placed. Maybe that could also help here.

**Comment by leiweibau** [comment]
You didn't ask for it, but I'll show you anyway. 😁 As you can see on the dashboard, there are options here to view log files. In the best case scenario, this could help me a little with future problems, provided they find their way into the database. However, with the 3 retries for WAN IP determination, this may no longer be necessary.

<img width="2860" height="1868" alt="Image" src="https://github.com/user-attachments/assets/0c17bf30-50ed-4bb0-8b11-5039747e6244" />

I am still working on the multilingual display.

**Comment by hspindel** [comment]
Is that dashboard in the current release?  I'm having trouble finding it. :-)

**Comment by leiweibau** [comment]
No, the dashboard will only be available with the next release.

**Comment by lastsamurai26** [comment]
i have the same problem since the update 
but i don't know why 

<img width="1471" height="276" alt="Image" src="https://github.com/user-attachments/assets/29348d90-5a25-42a0-b811-0ce1389808f0" />

Strangely enough, opnsense does not show me any downtime, and even the ONT did not log any offline status. 

i know that the bug is seams to be fixed (: but only as info

**Comment by leiweibau** [comment]
Should be fixed

```
Pi.Alert v2026-01-04
---------------------------------------------------------
Executing user: root
Timestamp: 2026-01-05 18:00:00

Retrieving Internet IP...
    Attempt 1: curl timeout
    Internet IP:  xxx.xxx.xxx.xxx

...
```

Here you can see that curl runs out of time

**Comment by hspindel** [comment]
I installed the latest update, and the issue persists.  It's not constant, but it is fairly frequent.

**Comment by leiweibau** [comment]
Can you show me a log? You can find it in the Dashboard.

**Comment by leiweibau** [comment]
A new update package is released

**Comment by hspindel** [comment]
I installed the latest update and the issue appears solved.  Which is very strange if all you did was revert to a previous version.  :-)

**Comment by leiweibau** [comment]
I have reversed the changes I made in version 2025-12-14. I had actually made these changes because I was having problems with WAN IP detection when I was doing my tests in VMs. So the idea was to make it more stable. It's unfortunate that it worked for me, but not for others. There will be another update tomorrow, as I am still fixing a few things that I didn't notice before.

... and thank you for your feedback
